# variables.tf

variable "libvirt-pool-name" {
  description = "the name of the pool defined in a root module."
}

variable "os-images" {
  description = "The libvirt volume for the base os image." 
}

variable "qemu_uri_path" {
  type = string
  description = "the URI of for qemu to use."
}

# Define the input variable, a more complex variable 
# https://developer.hashicorp.com/terraform/language/values/variables
# See https://developer.hashicorp.com/terraform/language/modules/develop/composition#conditional-creation-of-objects for details on dependency inversion.
variable "machines" {
  description = "A list of machine objects."
  type = map(object({
    hostname     = string
    ip_addr      = string
    disk_size    = number
    memory       = number
    vcpu         = number
    machine_type = string
    os = object({
      id = string
    })
    cloud-init = string
    network_config = string
  }))
}


variable "ip_gateway" {
  type = string
}

variable "hostname_prefix" { 
  type = string
}
# pw is generated by this python3 1-liner:
# python3 -c 'import crypt,getpass; print(crypt.crypt(getpass.getpass(), crypt.mksalt(crypt.METHOD_SHA512)))'
variable "root_pw" {
  type = string
  default = "the password hash from cmd"
}
variable "hypervisor_host" {
  description = "The fully qualified domain of your hypervisor host."  
  type = string
}
# pw is generated by this python3 1-liner:
# python3 -c 'import crypt,getpass; print(crypt.crypt(getpass.getpass(), crypt.mksalt(crypt.METHOD_SHA512)))'
variable "passwd_hash" {
  type = string
  default = "the password hash from cmd"
}
variable "ssh_pub_key" {
  type = string
  default = "my_public_ssh_key"
}
variable "my_user_name" {
  type = string
  default = "ubuntu"
}
variable "dns_domain_name" {
  type = string
  default = "co.slakin.net"
}
variable "dns_domain_one" {
  type = string
  default = "co.slakin.net"
}
variable "dns_domain_two" {
  type = string
  default = "co.slakin.net"  
}
variable "dns_ip_one" {
  type = string
  default = "172.16.1.11"
}
variable "dns_ip_two" {
  type = string
  default = "172.16.1.12"
}
variable "ip_bitmask" {
  type = string
  default = "24"
}
variable "ethernet_if" {
  type = string
  default = "eth0"
}

